### ISSUE TITLE
Add tick mark for the initial slider value

### ISSUE THREAD

**Issue by travisfranck** [climateinteractive/SDEverywhere#11]
It would be nice to have a  tick mark for the the initial slider value.  This would allow users to see a what has changed from defaults, and also allow them to move individual slides to their default values more easily.

**Comment by travisfranck** [comment]
I don't know if I would think of this too much as a "feature" that is arbitrary.  The main thing is that, for almost all (or all?) sliders it is useful to do know the default value.  Once a user moves it, they lose this information.  If SDE only does one kind of slider style, I suggest a 'tick' be the default.

**Comment by chrispcampbell** [comment]
@travisfranck: I think I was kind of using this issue to make a larger point that there's a slippery slope where if we add lots of fine tuning to the app template code, it potentially increases the complexity and "understandability" of the code.  I've been erring on the side of keeping the template as minimal as possible because I don't want SDE to get into the business of a once-size-fits-all (or even super configurable) app layout for model/simulator apps.  (It might be nice to have a standard UI component library for SDE, or maybe as a `@climateinteractive` thing, but that's a separate ball of wax.)

Anyway, my feelings about maintaining UI tweaks can be kept for a separate discussion thread.  I guess having a tick mark is a small thing to add, so I'll just reopen and fix and put philosophical stuff aside.  I'll note that in the current app template we already have track highlighting (like in En-ROADS), so when you move the slider, you don't lose track of the default value like you said above.  But having both track highlighting and a tick mark (like we have in En-ROADS) seems fine, and like I said, easy to add, so I'll just do it.  Screenshot below.

<img width="477" alt="image" src="https://user-images.githubusercontent.com/438425/197637333-339a945a-d97b-4d10-bea5-80a031eefc20.png">

**Comment by travisfranck** [comment]
Thanks.  I think the issue was written before track highlighting was implemented, but I think the tick mark is nice. 👍
