### ISSUE TITLE
Allow View at the top-level of menu

### ISSUE THREAD

**Issue by travisfranck** [climateinteractive/SDEverywhere#14]
It could be useful to have views that weren't nested.  For instance, maybe there is a main view ("Summary" below) that contains the default graphs, but other views are nested.  Example hierarchy:

* Simulation Menu
    * Summary View
    * Section 1
        * View 2
        * View 3
    * Section 2
        * View 4
    etc.
    
    With Summary View at the top level of the Simulation menu.

**Comment by chrispcampbell** [comment]
This issue is in reference to the old config file parsing / app generation code (`--genhtml`) that was included in SDE prior to version 0.7, which generated app code with a specific layout and menu structure that was inspired by En-ROADS.

With the new `plugin-config` and `create` packages (and the `template-default` app template), the user can choose whatever layout (or menu structure, etc) that makes sense for their model.  There's no one-size-fits-all structure that works for all models, so the current approach is to have a simple app template that can be customized by the user, because I don't think SDEverywhere should be in the business of providing lots of different UI-generation options.  (The CSV file format used by `plugin-config` does offer many fields that are useful for customizing the layout and menu structure for graphs and inputs in an application.)

So, I'm going to close this as "will not fix", but I'd be happy to accept new issues / PRs that provide alternative project templates that offer different layouts, menu structures, etc.

**Comment by travisfranck** [comment]
Does the plugin-config allow for two graphs side-by-side already?  Is this documented somewhere or is there any demo?  If not, maybe this is something I can work on.

**Comment by chrispcampbell** [comment]
@travisfranck: It's not so much about `plugin-config`, but you could edit `examples/template-default` so that it supports two side-by-side graphs by default.  It's mainly a matter of editing `index.html` to have a "left" and "right" containers (each with selector, graph, and legend).  Or better yet, configure that programmatically in `index.js` in the `initGraphsUI` function instead of baking it into the HTML file.  That way you could have it create either 1 or 2 graphs so that the developer can choose.

The reason I didn't just implement 2 side-by-side in the first place is that I was trying to keep the template small and simple, and I also wanted it to look nice by default on a phone-size screen.  If you do want to take a stab at adding this, I'd like it if the phone case is kept in mind (you could just show the left one and hide the right if the viewport gets smaller than say 500px.
