### ISSUE TITLE
"could not find commit hash for main" when running `npm create @sdeverywhere@latest`

### ISSUE THREAD

**Issue by MSDRL** [climateinteractive/SDEverywhere#460]
When trying to run the first instruction I am getting this:

```
C:\Users\Make_\Desktop\SDEverywhere-main\examples\sir\model>cd..
C:\Users\Make_\Desktop\SDEverywhere-main\examples\sir>npm create @sdeverywhere@latest
Welcome to SDEverywhere!
Let's create a new SDEverywhere project for your model.
√ Where would you like to create your new project? ... <current directory>
√ Using "C:\Users\Make_\Desktop\SDEverywhere-main\examples\sir" as the project directory.
√ Which template would you like to use? » Default project
× Copying project files...
could not find commit hash for main
**There was a problem copying the template.**
Please file a new issue with the command output here: https://github.com/climateinteractive/sdeverywhere/issues
C:\Users\Make_\Desktop\SDEverywhere-main\examples\sir>
```

Attaching a screenshot of the same issue. 
All I did was a clean node-v20.12.1-x64.exe installation (without additional packages) install, then followed your instructions. 
Any idea what to do? 
Thanks,
Mark

![SDeverywhereError](https://github.com/climateinteractive/SDEverywhere/assets/167337583/1d3520e9-dbc3-49a6-8131-881d2bddcf9f)

**Comment by chrispcampbell** [comment]
@MSDRL: Do you know (or can you check) whether you have Git installed already?  Like, if you type `git` in a command prompt and it reports an error, then it likely means Git is not already installed.

Note that the `@sdeverywhere/create` package currently requires Git and we have an open issue about that, see #389.  If this is the same issue that you're running into, then please let me know and I'll close this one as a duplicate.

**Comment by chrispcampbell** [comment]
@MSDRL: Sorry about this.  Your experience looks the same as described in #359.  My recollection is that restarting your machine/Windows would do the trick, to cause the environment to be reloaded so that the correct Python binary is picked up on the path.

If that still doesn't work, then the last resort is the same as the user described in #359: you can manually install Emscripten SDK, which isn't terribly daunting.  The reason we include the automated steps in the create script is mostly as a convenience, but also to ensure that a compatible version of the SDK is installed.

If you do try installing manually, I would recommend using these [instructions](https://emscripten.org/docs/getting_started/downloads.html#emsdk-install-targets) and install version 2.0.34 (which is what SDEverywhere uses by default), but 3.1.46 should also work (which is what we use to build En-ROADS).  Let me know how you make out.

**Comment by chrispcampbell** [comment]
As of v0.2.13, the `@sdeverywhere/create` package now works even if Git is not installed locally, so the initial error that was reported here ("could not find commit hash for main") should no longer occur.  See #464 for more details. This should reduce friction for non-technical users who are new to SDEverywhere, and my comments above about needing to install Git locally are no longer applicable; you can use SDEverywhere without having Git installed on your machine.

The issue with Python on Windows (when using `@sdeverywhere/create` to install Emscripten) is still unresolved, but is being tracked in #359 and I hope to resolve that before long.

Since these issues are being tracked elsewhere, I think it makes sense to close this one as a duplicate.

@MSDRL: Thanks for filing the issue.  Feel free to start a new [discussion](https://github.com/climateinteractive/SDEverywhere/discussions) if you need more help getting started with SDEverywhere.
