### ISSUE TITLE
Implement SAVEPER

### ISSUE THREAD

**Issue by ToddFincannon** [climateinteractive/SDEverywhere#5]
SDE should support the SAVEPER setting in MDL files. This means that variable values would be saved less frequently than the TIMESTEP. Support should mean smaller data structs/arrays and therefore less memory and faster passing of the structs (to UI).

I forget if right the code looks at previous array values during execution. If so, this could be a bigger change than simply making smaller arrays. But also, if execution assumes arrays, we could ditch the memory benefits and create parallel structures for data passing. Different form of "complicated".

(moved from WorldClimate issue #235 filed by Travis)

**Comment by chrispcampbell** [comment]
@ToddFincannonEI: I keep meaning to ask you about this issue.  It seems like maybe it just wasn't closed after you added SAVEPER support at the C level many years ago.  Do you happen to remember if this issue was being left open for a reason (like, if there's some deficiency in the way SAVEPER is handled at the C level)?  Or if it just wasn't closed after you added SAVEPER support?

**Comment by ToddFincannonEI** [comment]
Yes, it looks like the code to support `SAVEPER` in `runModelWithBuffers` implements this issue, so I think we can close it.

**Comment by chrispcampbell** [comment]
OK, closing this as "fixed" in the sense that it was already implemented at an earlier date for the native C level.  Note that I'm currently implementing support for non-1 `SAVEPER` values in the newer `runtime` and `runtime-async` packages, but that work is separate and being dealt with under #291.
